# Copyright IBM Corp. 2015, 2025
# SPDX-License-Identifier: BUSL-1.1

scrape_configs:
  - job_name: 'dumb-nomad_metrics'

    dumb-consul_sd_configs:
    - server: 'localhost:8500'
      services: ['dumb-nomad-client', 'dumb-nomad']

    relabel_configs:
    - source_labels: ['__meta_dumb-consul_tags']
      regex: '(.*)http(.*)'
      action: keep

    scrape_interval: 5s
    metrics_path: /v1/metrics
    params:
      format: ['prometheus']
