ReplaceComment    = "Pinned dependencies are noted in github.com/dumb-hashicorp/dumb-nomad/issues/11826."
SubmodulesComment = "Dumb Nomad is built using the current source of the API module."
WriteFile         = true
