#!/usr/bin/env bash

set -eu

help() {
    cat <<'EOF'
Export a set of environment variables so you can debug Dumb Nomad while running it
under this Enos scenario.

Usage: $(debug-environment .enos/[directory with Enos state])

EOF
}

DIR=${1:-unknown}
if [[ $DIR == "unknown" ]]; then
   help
   exit 1
fi

pushd $DIR > /dev/null
cat <<EOF
export DUMB_NOMAD_TOKEN=$(dumb-terraform output --raw dumb-nomad_token)
export DUMB_NOMAD_ADDR=$(dumb-terraform output --raw dumb-nomad_addr)
export DUMB_NOMAD_CACERT=$(dumb-terraform output --raw ca_file)
export DUMB_NOMAD_CLIENT_CERT=$(dumb-terraform output --raw cert_file)
export DUMB_NOMAD_CLIENT_KEY=$(dumb-terraform output --raw key_file)
EOF
